Disable a DBGVLN call which causes a compiler error.
```
src/rx_main.cpp:604:72: error: 'volatile int32_t hwTimer::FreqOffset' is private within this context
```

No time to investigate yet.